var username;
var myName = "Masood Alam";
var message;
message = "Hello World";
alert(message);
alert("Masood  Alam");
alert("19 Years Old");
alert("OraSoft Training Institute");
alert("a part Of Saylani Mass Training Program");
alert("PIZZA\nPIZZ\nPIZ\nPI\nP");
var numberOfChildren = "02";
var partnerName = "ABC";
var geographicLocation = "Mexico";
var jobTitle = "Software Engineer";
alert(" You will be a " + jobTitle + " in " + geographicLocation + " and married to " + partnerName + " with " + numberOfChildren + " kids " );
var email = "masood.alam.987@gmail.com";
alert("My email address is " + email);
var book = "A Smarter way to learn JavaScript";
alert("I'm trying to learn from the book " + book );
document.write("Yay! I can write HTML Through JavaScript");